-- Lumi's Hyprland Config
-- The Hyprland.lua file serves to source the other files to keep things modular, easy to navigate, and clean

require("Settings.monitors")
require("Settings.general")
require("Settings.decoration")
require("Settings.animations")
require("Settings.input")
require("Settings.gestures")
require("Settings.group")
require("Settings.misc")
require("Settings.layout")
require("Settings.binds")
require("Settings.xwayland")
require("Settings.opengl")
require("Settings.render")
require("Settings.cursor")
require("Settings.ecosystem")
require("Settings.quirks")
require("Settings.debug")
require("Settings.input-capture")
require("Settings.experimental")
require("Settings.keybinds")
require("Settings.windowrules")
require("Settings.workspacerules")
require("Settings.layerrules")
require("Settings.autostart")
