-- Group Settings

hl.config({
	auto_group = true,
	drag_into_group = 1,
	focus_removed_window = true,
	group_on_movetoworkspace = false,
	insert_after_current = true,
	merge_floated_into_tiled_on_groupbar = false,
	merge_groups_on_drag = true,
	merge_groups_on_groupbar = true,

	col = {
		border_active = "0x66ffff00",
		border_inactive = "0x66777700",
		border_locked_active = "0x66ff5500",
		border_locked_inactive = "0x66775500",
	},

	groupbar = {
		enabled = true,
		blur = false,
		disable_when_only = false,
		font_family = [[Empty]],
		font_size = 8,
		font_weight_active = "normal",
		font_weight_inactive = "normal",
		gaps_in = 2,
		gaps_out = 2,
		gradients = false,
		gradient_round_only_edges = true,
		gradient_rounding = 2,
		gradient_rounding_power = 2.0,
		height = 14,
		indicator_gap = 0,
		indicator_height = 3,
		keep_upper_gap = true,
		middle_click_close = true,
		priority = 3,
		render_titles = true,
		round_only_edges = true,
		rounding = 1,
		rounding_power = 2.0,
		scrolling = true,
		stacked = false,
		text_color = "0xffffffff",
		text_color_inactive = "0xffffffff",
		text_color_locked_active = "0xffffffff",
		text_color_locked_inactive = "0xffffffff",
		text_offset = 0,
		text_padding = 0,

		col = {
			active = "0x66ffff00",
			inactive = "0x66777700",
			locked_active = "0x66ff5500",
			locked_inactive = "0x66775500",
		},
	},
})
