-- Misc Settings

hl.config({
	misc = {
		allow_session_lock_restore = false,
		always_follow_on_dnd = true,
		animate_manual_resizes = false,
		animate_mouse_windowdragging = false,
		anr_missed_pings = 5,
		background_color = "0x111111",
		close_special_on_empty = true,
		disable_autoreload = false,
		disable_hyprland_guiutils_check = false,
		disable_hyprland_logo = false,
		disable_scale_notification = false,
		disable_splash_rendering = true,
		disable_watchdog_warning = false,
		disable_xdg_env_checks = false,
		enable_anr_dialog = true,
		enable_swallow = false,
		exit_window_retains_fullscreen = 0,
		focus_on_activate = false,
		font_family = "Sans",
		force_default_wallpaper = -1,
		initial_workspace_token_timeout = 10,
		initial_workspace_tracking = 1,
		key_press_enables_dpms = false,
		layers_hog_keyboard_focus = true,
		lockdead_screen_delay = 1000,
		middle_click_paste = true,
		mouse_move_enables_dpms = false,
		mouse_move_focuses_monitor = true,
		name_vk_after_proc = true,
		on_focus_under_fullscreen = 2,
		render_unfocused_fps = 15,
		screencopy_force_8b = true,
		session_lock_blur = false,
		session_lock_xray = false,
		size_limits_tiled = false,
		splash_font_family = [[Empty]],
		swallow_exception_regex = [[Empty]],
		swallow_regex = [[Empty]],
		vrr = 0,

		col = {
			splash = "0x55ffffff",
		},
	},
})
